account/urls.py
from django.urls import path
from account.views import RegisterUserView, UserLoginView, UserLogoutView, \
    ChangeUserDetailsView, OrderHistoryView, DashboardView

app_name = 'account'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('user_edit/<int:pk>/', ChangeUserDetailsView.as_view(), name='user_edit'),
    path('user_dashboard/', DashboardView.as_view(), name='user_dashboard'),
    path('order_history/', OrderHistoryView.as_view(), name='order_history'),
    # path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

cafe/api/urls.py
from django.urls import path
from rest_framework import routers
from cafe.api.resources import MenuListAPIView, OrderAPIVIewSet, OrderItemAPIVIewSet

router = routers.SimpleRouter()
router.register(r'order', OrderAPIVIewSet)
router.register(r'orderitems', OrderItemAPIVIewSet)
urlpatterns = router.urls

urlpatterns += [
    path('menu/', MenuListAPIView.as_view()),
    path('menu/<int:id>/', MenuListAPIView.as_view()),
    # path('order/', OrderAPIVIew.as_view().as_view()),
]

cafe/urls.py
from django.urls import path
from .views import ProductDetailView, Index, delivery_terms, CartView, \
    CheckOut, payment_success, payment_fail, apply_coupon, LocationView, ReorderView, OrderPDF

app_name = 'cafe'

urlpatterns = [
    path('cafe/recreate-order/', ReorderView.as_view(), name='reorder'),
    path('cafe/location/', LocationView.as_view(), name='location'),
    path('cafe/cart/', CartView.as_view(), name='cart'),
    path('cafe/update-cart/', CartView.as_view(), name='update-cart'),
    path('cafe/product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('cafe/delivery_terms/', delivery_terms, name='delivery_terms'),
    path('cafe/checkout/', CheckOut.as_view(), name='checkout'),
    path('cafe/payment_success/', payment_success, name='payment_success'),
    path('cafe/payment_fail/', payment_fail, name='payment_fail'),
    path('cafe/order_pdf/', OrderPDF.as_view(), name='order_pdf'),
    path('cafe/apply_coupon/', apply_coupon, name='apply_coupon'),
    path('cafe/<str:group>/', Index.as_view(), name='main_page'),
    path('', Index.as_view(), name='main_page'),
]

pirosmani/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('', include('cafe.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('api/account/', include('account.api.urls')),
    path('api/cafe/', include('cafe.api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cafe/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

from account.models import Customer, CustomerAdd, User
from cafe.utils import MIN_DISCOUNT_OF_COUPON, MAX_DISCOUNT_OF_COUPON


class Menu(models.Model):
    name = models.CharField(max_length=50)
    picture = models.FileField(upload_to='menu/')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='наименование')
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, verbose_name="описание")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    weight = models.CharField(max_length=255, default=0)
    picture = models.ImageField(upload_to='products/', default='products/no-mpphoto.jpg')
    group = models.ForeignKey(Menu, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cafe:product_detail', args=[self.slug, ])


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    is_completed = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=10)
    date_ordered = models.DateTimeField(auto_now=True)

    @property
    def get_order_cost(self):
        order_items = self.orderitems_set.all()
        order_cost = sum([item.get_items_cost for item in order_items])
        return order_cost

    @property
    def get_oder_quantity(self):
        order_items = self.orderitems_set.all()
        order_quantity = sum([item.quantity for item in order_items])
        return order_quantity

    # def get_user_order_history(self):
    #     user_orders = self.objects.filter(customer__user_id=self.customer.user_id)
    #     return user_orders

    def __str__(self):
        return str(f'{self.customer} - {self.transaction_id} - {self.is_completed}')


# class OrderManager(models.Manager):
#     def get_queryset(self):
#         return super(OrderManager, self).get_queryset().filter(Customer.user)


class OrderItems(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

    @property
    def get_items_cost(self):
        items_cost = self.quantity * self.product.price
        return items_cost

    def __str__(self):
        return str(f'{self.order} - {self.product}')


class Coupon(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    code = models.CharField(max_length=15, unique=True)
    discount = models.IntegerField(
        validators=[
            MinValueValidator(MIN_DISCOUNT_OF_COUPON),
            MaxValueValidator(MAX_DISCOUNT_OF_COUPON)
        ])
    valid_from = models.DateTimeField()
    valid_until = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    is_used = models.BooleanField(default=False)

    def __str__(self):
        return self.code

    @property
    def is_coupon_valid(self):
        current_date = timezone.now()
        return (self.valid_from < current_date < self.valid_until) and self.is_active and (not self.is_used)

cafe/views.py
import json
import math
import braintree
import requests
import weasyprint
from decimal import Decimal
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import DetailView, ListView
from django.conf import settings
from .mixins import ContextMixin, CartActionsMixin
from .models import Product, Order, OrderItems, Coupon
from .tasks import transaction_email_notification


class Index(ContextMixin, ListView):
    """shows the index page with dishes"""
    template_name = 'cafe/index.html'
    context_object_name = 'offer'

    def get_queryset(self):
        group = self.kwargs.get('group')
        if group:
            queryset = Product.objects.filter(group_id=group)
        else:
            queryset = Product.objects.all()
        return queryset


class ProductDetailView(ContextMixin, DetailView):
    """shows detals for dish including comments calories and description"""
    model = Product
    context_object_name = 'product'
    template_name = 'cafe/product_detail.html'


class CartView(CartActionsMixin, ContextMixin, ListView):
    template_name = 'cafe/cart.html'
    context_object_name = 'cart_content'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            customer = self.request.user
            order, created = Order.objects.get_or_create(customer=customer, is_completed=False)
            cart_content = order.orderitems_set.filter(quantity__gt=0)

        else:
            cart_content = self.get_cookie_cart_content()
            if cart_content:
                cart_content = [
                    {
                        'id': int(key),
                        'name': Product.objects.get(id=key).name,
                        'picture': Product.objects.get(id=key).picture,
                        'quantity': value,
                        'price': Product.objects.get(id=key).price,
                        'item_value': Product.objects.get(id=key).price * value
                    } for key, value in cart_content.items()]
            else:
                cart_content = {}
        return cart_content

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            customer = self.request.user
            order, created = Order.objects.get_or_create(customer=customer, is_completed=False)
            total_value = order.get_order_cost
        else:
            cart_content = self.get_cookie_cart_content()
            total_value = sum(
                [Product.objects.get(id=article).price * quantity for article, quantity in cart_content.items()]
            )
        context_data = super(CartView, self).get_context_data()
        context_data['total_value'] = total_value
        return context_data

    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        product_id = data['productId']
        cart = Cart(product_id, request)
        action = data['action']
        if action == 'add':
            cart_info = cart.add_item()
        elif action == 'remove':
            cart_info = cart.subtract_item()
        elif action == 'removeOrderItem':
            cart_info = cart.delete_item()
        else:
            raise ValueError('unknown command')
        response = JsonResponse(cart_info[0], safe=False)
        if request.user.is_anonymous:
            response.set_cookie('cart', json.dumps(cart_info[1]))
        return response


class Cart(CartActionsMixin):
    """
    if user is authenticated we keep cart in database alternatively we keep it in cookies
    """

    def __init__(self, product_id, request):
        self.request = request
        self.product_id = product_id
        self.product = get_object_or_404(Product, id=self.product_id)

        if request.user.is_authenticated:
            self.order, self.created = Order.objects.get_or_create(
                customer=self.request.user,
                is_completed=False
            )
            self.cart = self.order.orderitems_set.filter(quantity__gt=0)

        else:
            self.cart = self.get_cookie_cart_content()

    def get_cart_info_anonymous_user(self, cart, product_id=None):
        quantity = cart.get(product_id, 0)
        if product_id:
            product = Product.objects.get(id=product_id)
            total_item = quantity * product.price
        else:
            total_item = 0
        pcs_ordered = sum([pcs for pcs in cart.values()])
        grand_total = sum(
            [Product.objects.get(id=article).price * quantity for article, quantity in cart.items()]
        )
        cart_info = self.make_cart_info(quantity, total_item, product_id, pcs_ordered, grand_total)
        return cart_info

    def get_cart_info_registered_user(self, item=None, order=None, product_id=None):
        quantity = item.quantity if item else 0
        total_item = item.get_items_cost if item else 0
        pcs_ordered = self.order.get_oder_quantity
        grand_total = self.order.get_order_cost
        cart_info = self.make_cart_info(quantity, total_item, product_id, pcs_ordered, grand_total)
        return cart_info

    @staticmethod
    def make_cart_info(quantity, total_item, product_id, pcs_ordered, grand_total):
        cart_info = {
            'quantity': quantity,
            'total_item': total_item,
            'productId': product_id,
            'pcs_ordered': pcs_ordered,
            'grand_total': grand_total
        }
        return cart_info

    def add_item(self):
        if self.request.user.is_authenticated:
            item, created = OrderItems.objects.get_or_create(
                order=self.order,
                product=self.product,
                defaults={'quantity': 1})
            if not created:
                item.quantity += 1
                item.save()
            cart_info = self.get_cart_info_registered_user(item, self.order, self.product_id)
        else:
            self.cart[self.product_id] = self.cart.get(self.product_id, 0) + 1
            cart_info = self.get_cart_info_anonymous_user(self.cart, self.product_id)
        return cart_info, self.cart

    def subtract_item(self):
        if self.request.user.is_authenticated:
            item = OrderItems.objects.get(order=self.order, product=self.product)
            item.quantity -= 1
            item.save()
            if item.quantity <= 0:
                item.delete()
            cart_info = self.get_cart_info_registered_user(item, self.order, self.product_id)
        else:
            self.cart[self.product_id] = self.cart.get(self.product_id) - 1
            if self.cart[self.product_id] <= 0:
                del self.cart[self.product_id]
            cart_info = self.get_cart_info_anonymous_user(self.cart, self.product_id)
        return cart_info, self.cart

    def delete_item(self):
        if self.request.user.is_authenticated:
            item = OrderItems.objects.get(order=self.order, product=self.product)
            item.delete()
            cart_info = self.get_cart_info_registered_user(order=self.order)
        else:
            del self.cart[self.product_id]
            cart_info = self.get_cart_info_anonymous_user(cart=self.cart)
        return cart_info, self.cart


class CheckOut(View):
    """checkout and payment"""

    def get(self, request):
        client_token = braintree.ClientToken.generate()
        order = Order.objects.get(customer=request.user, is_completed=False)
        order_items = OrderItems.objects.filter(order=order)
        context = {
            'client_token': client_token,
            'order': order,
            'order_items': order_items
        }
        return render(request, 'cafe/checkout.html', context)

    def post(self, request):
        nonce = self.request.POST.get('payment_method_nonce')
        amount = Decimal(self.request.POST.get('amount').replace(',', '.'))
        result = braintree.Transaction.sale({
            'amount': amount,
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })

        if result.is_success:
            order = Order.objects.get(customer=request.user, is_completed=False)
            order.is_completed = True
            order.transaction_id = result.transaction.id
            order.save()
            #  transaction_email_notification(request.user)
            return redirect('cafe:payment_success')
        else:
            # return JsonResponse({'success': False, 'message': result.message})
            return redirect('cafe:payment_fail')


def apply_coupon(request):
    data = json.loads(request.body)
    coupon_code = data['couponCode']
    coupon = Coupon.objects.filter(code=coupon_code)[0]
    if coupon:
        if coupon.is_coupon_valid:
            coupon.owner = request.user
            coupon.save()
            discount = coupon.discount
        else:
            discount = -1
    else:
        discount = 0
    return JsonResponse({"discount": discount}, safe=False)


def payment_success(request, pdf_data):
    return render(request, 'cafe/payment_success.html', context={'pdf_data': pdf_data})


def payment_fail(request):
    return render(request, 'cafe/payment_fail.html')


class ReorderView(View):

    def get(self, request):
        new_order, created = Order.objects.get_or_create(customer=request.user, is_completed=False)
        order_id = request.GET.get('order_id')
        order_items = OrderItems.objects.filter(order_id=order_id)
        for item in order_items:
            OrderItems.objects.create(order=new_order, product=item.product, quantity=item.quantity)
        return redirect('cafe:cart')


def delivery_terms(request):
    return render(request, 'cafe/delivery_terms.html')


class LocationView(View):

cafe/templates/cafe/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Title
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'cafe/css/main.css' %}">
    {% block jstop %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>

<header>
    <div class="container">
        <div class="header_row">
            <div class="h_first_logo">
                <a href="{% url 'cafe:main_page' %}"><img class="h_img"
                                                          src="{% static 'cafe/images/details/h_first_logo1.jpg' %}"
                                                          alt="cafe"></a>
            </div>
            <div class="h_second_logo">
                <a href="{% url 'cafe:main_page' %}"><img class="h_img"
                                                          src="{% static 'cafe/images/details/h_second_logo1.jpg' %}"
                                                          alt="cafe"></a>
            </div>
            <div class="h_gap_1"></div>
            <nav class="h_menu">
                <ul class="h_menu_list">
                    <li>
                        <div class="dropdown">
                            <button class="dropbtn">Menu</button>
                            <div class="dropdown-content">

                                {% for item in main_menu %}
                                    <a href="{% url 'cafe:main_page' group=item.id %}"><img class="dropdown-img"
                                                                                            src="{{ item.picture.url }}"
                                                                                            alt="pic">{{ item }}</a>
                                {% endfor %}

                            </div>
                        </div>
                    </li>
                    <li class="disappear"><a href="{% url 'cafe:delivery_terms' %}">Project Details</a></li>
                    <li class="disappear"><a href="{% url 'cafe:location' %}">Location</a></li>
                    <li class="disappear"><a href="#">Booking</a></li>
                </ul>
            </nav>

            <div class="h_phone">
                <a href="tel:5551234567"><img src="{% static 'cafe/images/details/phone.svg' %}" alt="Call 5551234567" />+88 888 888-88-88</a>
{#                <img src="{% static 'cafe/images/details/phone.svg' %}" alt="phone"> +88 888 888-88-88#}

            </div>
            <div class="h_icons">
                <div class="h_login">
                    {% if user.is_authenticated %}
                        <div class="h_login_inner">
                            <a href="{% url 'account:user_dashboard' %}">account</a>
                        </div>
                    {% else %}
                        <a href="{% url 'account:login' %}">
                            <img class="h_img start-btn" src="{% static 'cafe/images/details/person.svg' %}" alt="person">
                        </a>
                    {% endif %}
                </div>

            <div class="h_basket">
                <a href="{% url 'cafe:cart' %}">
                    <img class="h_img" src="{% static 'cafe/images/details/shopping-cart.svg' %}" alt="cart"/>
                    <span id="cart_indicator" class="cart_indicator">{% if order_quantity > 0 %}
                        {{ order_quantity }} {% endif %}</span>
                    <div class="order_total_figure">{% if order_value > 0 %} {{ order_value }} {% endif %} </div>
                </a>
            </div>
            </div>
        </div>
    </div>
</header>

<section class="promo">
    {% block promo %}
    {% endblock %}
</section>

<section class="menu">
    {% block menu %}
    {% endblock %}

</section>

<section class="main">
    {% block main_content %}
    {% endblock %}
</section>

{#<section class="paginator">#}
{#    {% block paginator %}#}
{#    {% endblock %}#}
{#</section>#}

<section class="video">
    {% block video %}
    {% endblock %}
</section>

<section class="delivery">
    {% block delivery %}
    {% endblock %}
</section>

<footer class="footer">
    <div class="container">
        <div class="footer-top">
            <div class="footer-top-contact">
                <div class="ftc-phones">
                    <div class="text1">call us</div>
                    <div class="text1">for orders:</div>
                    <div class="phone1">+44 282-60-00</div>
                    <div class="phone1">+44 066-46-85</div>
                </div>
                <div class="ftc-working">Working hours: 9:00 a.m till 18:00 p.m.</div>
                <div class="ftc-email">Email: whoknows@.whoknows.com</div>
            </div>
            <div class="footer-top-social"></div>
        </div>
        <div class="footer-bottom">
            <div class="support">
{#                <div class="support-title">Support</div>#}
                <div class="support-items">
                    <div class="support-items-copyright">©2020. Unknown</div>
                    <div class="support-items-terms">Terms and agreements</div>
                    <div class="support-items-policy">Privacy policy</div>
                </div>
            </div>
        </div>
    </div>
</footer>


{% block jscode %}
{% endblock %}

</body>
</html>

cafe/templates/cafe/cart.html
{% extends 'cafe/base.html' %}
{% load static %}
{% load get_product_value %}

{% block title %}
    Корзина
{% endblock %}

{% block jstop %}
    <script>
        let user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getToken('csrftoken');
    </script>
{% endblock %}

{% block main_content %}
    <div class="container">
        <div class="body_cart">
            <div class="left">
                <div class="title_cart">Cart</div>
                {% if request.user.is_authenticated %}
                    {% if cart_content %}
                        {% for item in cart_content %}
                            <div class="cart idd{{ item.product_id }}">
                                <div class="cart-group-one">
                                    <div data-cart_cancel="{{ item.product.id }}" class="cart_cancel">
                                        <img class="cart_cancel_img"
                                             src="{% static 'cafe/images/details/cart_cancel.svg' %}" alt="cart_cancel">
                                    </div>
                                    <div class="cart_picture">
                                        <img src="{{ item.product.picture.url }}" alt="product_picture">
                                    </div>
                                    <div class="cart_item">{{ item.product }}</div>
                                </div>
                                <div class="cart-group-two">
                                    <div class="cart_item_cost">
                                        {{ item.product.price }} x
                                    </div>
                                    <div class="cart_quantity">
                                        <div data-product="{{ item.product.id }}" data-action="remove"
                                             class="card_quantity_arrow update-cart">-
                                        </div>
                                        <div data-counter class="card_quantity_data">{{ item.quantity }}</div>
                                        <div data-product="{{ item.product.id }}" data-action="add"
                                             class="card_quantity_arrow update-cart">+
                                        </div>
                                    </div>
                                    <div data-item_total class="cart_price">{{ item.get_items_cost }} uah</div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div>Your cart is empty</div>
                    {% endif %}

                {% else %}
                    {% if cart_content %}
                        {% for item in cart_content %}
                            <div class="cart idd{{ item.id }}">
                                <div class="cart-group-one">
                                    <div data-cart_cancel="{{ item.id }}" class="cart_cancel">
                                        <img class="cart_cancel_img" alt="cart_cancel"
                                             src="{% static 'cafe/images/details/cart_cancel.svg' %}">
                                    </div>
                                    <div class="cart_picture">
                                        <img src="{{ item.picture.url }}" alt="item picture">
                                    </div>
                                    <div class="cart_item">{{ item.name }}</div>
                                </div>
                                <div class="cart-group-two">
                                    <div class="cart_item_cost">
                                        {{ item.price }} x
                                    </div>
                                    <div class="cart_quantity">
                                        <div data-product="{{ item.id }}" data-action="remove"
                                             class="card_quantity_arrow update-cart">-
                                        </div>
                                        <div data-counter class="card_quantity_data">{{ item.quantity }}</div>
                                        <div data-product="{{ item.id }}" data-action="add"
                                             class="card_quantity_arrow update-cart">+
                                        </div>
                                    </div>
                                    <div data-item_total class="cart_price">
                                        {{ item.item_value }} uah
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div>Your cart is empty</div>
                    {% endif %}
                {% endif %}
            </div>
            <div class="order-delivery">
                {% if cart_content %}
                    <div class="right">
                        <div class="oder">
                            <div class="order_number">
                                Order # {{ order.transaction_id }}
                            </div>
                            <div class="order_card">
                                <div class="order_quantity">
                                    <div class="order_quantity_title">Total:</div>
                                    <div class="order_quantity_figure">
                                        {{ order_value }} uah
                                    </div>
                                </div>
                                {#                                <div class="order_total">#}
                                {#                                    <div class="order_total_title">Total</div>#}
                                {#                                    <div data-total_checkout class="order_total_figure">{{ order_value }} uah</div>#}
                                {#                                </div>#}
                                {% if request.user.is_authenticated %}
                                    <button id="place_order_btn" class="order_btn btn">Checkout</button>
                                {% else %}
                                    <button id="login_place_order_btn" class="order_btn btn">Login to proceed</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        document.getElementById("#login_place_order_btn").addEventListener("click", function () {
            window.location.href = "{% url 'account:login' %}";
        });
    </script>
    <script>
        document.getElementById("place_order_btn").addEventListener("click", function () {
            window.location.href = "{% url 'cafe:checkout' %}";
        });
    </script>
{% endblock %}

{% block jscode %}
    <script src="{% static 'cafe/js/main.js' %}"></script>
{% endblock %}

cafe/templates/cafe/delivery.html
{% load static %}

  <div class="container">
    <div class="deliver-row">
      <div class="divery-context">
        <div class="delivery-context-text">
          <p>Free delivery within unknown city area if order exceeds 1000 uah</p>
        </div>
{#        <button class="delivery-btn">#}
{#          Enroll#}
{#        </button>#}
      </div>
      <div class="delivery-picture">
        <img src="{% static 'cafe/images/details/nissan-nv-cargo-s-cargo-van-side-view 1.jpg' %}">
      </div>
    </div>
  </div>

cafe/templates/cafe/delivery_terms.html
{% extends 'cafe/base.html' %}
{% load static %}

{% block main_content %}

    <div class="container" style="margin-right: 50px">
        <ol>
            <li>custom users - admin, shop admin, and customer</li>
            <li>cart is stored in database for registered users and in cookies for anonymous</li>
            <li>cart history view, order repeat based previous order</li>
            <li>open pdf invoice of any previous purchase</li>
            <li>pdf invoice generation via weasyprint</li>
            <li>payment integration with sandbox braintree</li>
            <li>user location based ip address, determine the closest cafe to user</li>
            <li>postgres bd</li>
            <li>celery - redis</li>
            <li>setting: development, production, base</li>
            <li>html, css - made based figma design</li>
        </ol>
    </div>

{% endblock %}

cafe/templates/cafe/paginator.html
  <div class="container">
    <div class="page-row">
      <div class="pages">
        <div class="page">s</div>
        <div class="page-1 page">1</div>
        <div class="page">
          2
        </div>
        <div class="page">8</div>
        <div class="page">></div>
      </div>
    </div>
  </div>

cafe/templates/cafe/payment_fail.html
{% extends 'cafe/base.html' %}

{% block main_contentdelivery %}
    <h2 class="container">Your payment failed</h2>
    <div></div>
    <div>you will be redirected to the main page</div>
    <script>
        setTimeout(function () {
            window.location.href = "{% url 'cafe:main_page' %}";
        }, 5000);
    </script>
{% endblock %}